name: open_sky_weather
description: Beautiful weather application widget

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  font_awesome_flutter: ^9.0.0
  flutter_html: ^2.2.1
  flutter_svg: ^0.22.0
  flutter_screenutil: ^5.0.0+2
  firebase_analytics: ^9.1.12
  firebase_crashlytics: ^2.8.4
  firebase_messaging: ^11.4.4
  get: ^4.1.4
  get_it: ^6.0.0
  get_storage: 2.0.3
  geolocator: ^7.4.0
  geocoding: 2.0.0
  internet_connection_checker: ^1.0.0+1
  in_app_review: ^2.0.3
  intl: ^0.17.0
  jiffy: ^4.1.0
  lint: ^1.0.0
  percent_indicator: ^3.0.1
  package_info: ^2.0.0
  pull_to_refresh: ^2.0.0
  sqflite: ^2.0.0+3
  url_launcher: ^6.0.3
  vibration: 1.7.4-nullsafety.0
  # percent_indicator: "^2.1.7+2"
  # flutter_staggered_animations: ^1.0.0
  # firebase_core: "^1.5.0"
  # firebase_messaging: "^10.0.6"
  # firebase_analytics: "^8.3.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Light.otf
          weight: 200
        - asset: assets/fonts/Metropolis-Regular.otf
          weight: 300
        - asset: assets/fonts/Metropolis-Medium.otf
          weight: 400
        - asset: assets/fonts/Metropolis-Bold.otf
          weight: 700
